apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp-container
        image: joadriancr/nodejs_app:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: nodejsapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001

